#!/usr/bin/python3

from random import uniform as u

pi_2 = 1.570796326794896619231321691639751442098584699687552910487

name = input('Base Filename: ').replace(' ', '_')
num  = int(input('Number of test cases: '))

with open('{}_{}'.format(name,num),'w') as f:
	f.write('{}\n'.format(num))
	for i in range(num):
		f.write('{}\n'.format(u(0, pi_2)))
