#!/usr/bin/python3

from random import uniform as u, randint as r

name = input('Base Filename: ').replace(' ', '_')
num  = int(input('Number of test cases: '))
m    = float(input('Minimum value of x: '))
M    = float(input('Maximum value of x: '))

with open('{}_{}_({})-({})'.format(name, num, m, M),'w') as f:
	f.write('{}\n'.format(num))
	for i in range(num):
		f.write('{}\n'.format(u(m, M)))
